name: Salesforce Deploy and Test

on:
  push:
    branches:
      - main

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        uses: salesforcecli/setup-sfdx@v1

      - name: Authenticate to Salesforce via SFDX URL (sf CLI)
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > sfdx_auth_url.txt
          sf org login sfdx-url --sfdx-url-file sfdx_auth_url.txt --alias myOrg --set-default

      - name: Check deployment directory
        run: ls -R force-app/main/default

      - name: Deploy to Salesforce
        run: |
          sf project deploy start --source-dir force-app/main/default --wait 10 --test-level RunLocalTests --target-org myOrg

      - name: Run Apex tests
        run: |
          sf apex test run --wait 10 --result-format human --target-org myOrg
