name: Salesforce Deploy and Test

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        uses: salesforcecli/setup-sfdx@v1

      - name: Authenticate to Salesforce Org via SFDX Auth URL
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > sfdx_auth_url.txt
          sfdx auth:sfdxurl:store --sfdx-url-file sfdx_auth_url.txt --set-default-username
          # This sets default username for all commands in this session
  - name: Deploy source to Salesforce
        run: |
          sf project deploy start --source-dir force-app --target-org heyMynk --wait 10 --json

      - name: Run Apex tests and wait for results
        run: |
          sf apex test run --target-org heyMynk --wait 10 --result-format human
