name: Salesforce Deploy and Test

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        uses: salesforcecli/setup-sfdx@v1

      - name: Authenticate to Salesforce Org via SFDX Auth URL
  env:
    SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
  run: |
    echo "$SFDX_AUTH_URL" > sfdx_auth_url.txt
    sfdx auth:sfdxurl:store --sfdx-url-file sfdx_auth_url.txt --set-default-dev-hub

      - name: Deploy source to Salesforce
        run: |
          sfdx force:source:deploy -p force-app -w 10 --testlevel RunLocalTests

      - name: Run Apex tests explicitly (optional if you want test report)
        run: |
          sfdx force:apex:test:run --resultformat human --wait 10

      - name: Get test results (optional)
        run: |
          sfdx force:apex:test:report --outputdir test-results --wait 10
